/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Marrakech Nocturne — design system tokens
        "surface": "#fdf9f4",
        "surface-dim": "#ddd9d5",
        "surface-bright": "#fdf9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3ee",
        "surface-container": "#f1ede8",
        "surface-container-high": "#ebe8e3",
        "surface-container-highest": "#e6e2dd",
        "surface-variant": "#e6e2dd",
        "on-surface": "#1c1c19",
        "on-surface-variant": "#56423c",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f4f0eb",
        "outline": "#89726b",
        "outline-variant": "#dcc1b8",
        "surface-tint": "#9d4222",
        "primary": "#9a4020",
        "on-primary": "#ffffff",
        "primary-container": "#ba5736",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb59d",
        "secondary": "#855402",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffbd69",
        "on-secondary-container": "#774a00",
        "tertiary": "#795346",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#956b5d",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59d",
        "on-primary-fixed": "#390b00",
        "on-primary-fixed-variant": "#7e2c0d",
        "secondary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#fcba66",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-fixed-dim": "#eebbab",
        "on-tertiary-fixed": "#2f140a",
        "on-tertiary-fixed-variant": "#623e32",
        "background": "#fdf9f4",
        "on-background": "#1c1c19",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "unit": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-lg": "48px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "serif": ["Playfair Display", "serif"],
        "sans": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
