name = "comptoir-darna-reservation"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# Variables non-sensibles (visibles dans le dashboard, pas de secrets ici)
[vars]
RESTAURANT_EMAIL ="perrydoyigbe197@gmail.com" 
# "reservation@comptoirdarna.com" # à remplacer par la vraie adresse
FROM_EMAIL = "onboarding@resend.dev"  # "reservations@comptoirdarna.com"       # domaine vérifié sur Resend
ALLOWED_ORIGIN ="https://comptoir-darna.vercel.app"
 #"http://localhost:5173/"     # domaine du frontend en prod

# Secrets à définir avec :
#   wrangler secret put RESEND_API_KEY
